version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    directory: "/"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "io.jsonwebtoken:jjwt-*"
      - dependency-name: "org.springframework.*:spring-*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "sunday"
