name: Deploy

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Run number to deploy from'
        required: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: prod
        url: https://demostore.gatling.io
    timeout-minutes: 10
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PROD_DEMOSTORE }}
          aws-region: us-east-1

      - name: Tag Docker image for production use
        env:
          ECR_REPOSITORY: demostore
          IMAGE_TAG: prod
          IMAGE_VERSION: build-${{ github.event.inputs.run_number }}
        run: |
          manifest=$(aws ecr batch-get-image \
            --repository-name $ECR_REPOSITORY \
            --image-ids imageTag=$IMAGE_VERSION \
            --output json \
              | jq --raw-output \
                   --join-output '.images[0].imageManifest')
          aws ecr put-image \
            --repository-name $ECR_REPOSITORY \
            --image-tag $IMAGE_TAG \
            --image-manifest "$manifest" \
              | jq --raw-output

      - name: Deploy
        run: |
          aws ssm start-associations-once --association-id "${{ secrets.AWS_SSM_ASSOCIATION_MEP_DEMOSTORE_PROD }}"
